name: Build and Publish Container

on: [push, workflow_dispatch]

permissions:
    checks: write # Required for test reporting
    contents: write # Required for pushing tags

jobs:
  build:
    # Available runners: https://github.com/actions/runner-images
    runs-on: ubuntu-24.04

    steps:
      - id: version
        name: Get semantic version
        uses: spritely/actions.semantic-version/get@438727427723967c0351b4da7cc717bbbb14416c # v0.8.10
        with:
          writeSummary: true

      - name: Create .env for build
        shell: bash
        run: touch ./.devcontainer/.env

      - name: Run tests
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
        with:
          runCmd: |
            bats --report-formatter junit --output . ./tests/
          push: never

      - name: Generate test report
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3.0.0
        if: always()
        with:
          name: Test Results
          path: report.xml
          reporter: java-junit

      - name: Build and publish container
        uses: spritely/actions.publish-container@304be251d3b48dd296d4ff2ff0040fa001f544ec # v0.2.73
        with:
          registryUsername: ${{ secrets.DOCKER_HUB_USERNAME }}
          registryPassword: ${{ secrets.DOCKER_HUB_TOKEN }}
          registryHost: docker.io
          context: ./src
          dockerfile: ./src/Containerfile
          imageNames: spritelydev/node24-devcontainer
          version: ${{ steps.version.outputs.version }}
          writeSummary: true

      - name: Apply semantic version
        if: ${{ steps.version.outputs.branchName == github.event.repository.default_branch }}
        uses: spritely/actions.semantic-version/apply@438727427723967c0351b4da7cc717bbbb14416c # v0.8.10
        with:
          version: ${{ steps.version.outputs.version }}
