name: Build and Publish Container

on: [push, workflow_dispatch]

permissions:
    checks: write # Required for test reporting
    contents: write # Required for pushing tags

jobs:
  build:
    # Available runners: https://github.com/actions/runner-images
    runs-on: ubuntu-24.04

    steps:
      - id: version
        name: Get semantic version
        uses: spritely/actions.semantic-version/get@5bc034299bcb31cc26f4c47e9dffa07c8d204699 # v0.7.6
        with:
          writeSummary: true

      - name: Create .env for build
        shell: bash
        run: touch ./.devcontainer/.env

      - name: Run tests
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6 # v0.3.1900000417
        with:
          runCmd: |
            bats --report-formatter junit --output . ./tests/
          push: never

      - name: Generate test report
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3.0.0
        if: always()
        with:
          name: Test Results
          path: report.xml
          reporter: java-junit

      - name: Build and publish container
        uses: spritely/actions.publish-container@b1c3099b5b3db8f6672f7381d5770f9829148194 # v0.2.8
        with:
          registryUsername: ${{ secrets.DOCKER_HUB_USERNAME }}
          registryPassword: ${{ secrets.DOCKER_HUB_TOKEN }}
          registryHost: docker.io
          context: ./src
          dockerfile: ./src/Containerfile
          imageNames: spritelydev/dotnet10-devcontainer
          version: ${{ steps.version.outputs.version }}
          writeSummary: true

      - name: Apply semantic version
        if: ${{ steps.version.outputs.branchName == github.event.repository.default_branch }}
        uses: spritely/actions.semantic-version/apply@5bc034299bcb31cc26f4c47e9dffa07c8d204699 # v0.7.6
        with:
          version: ${{ steps.version.outputs.version }}
